name: Cherry

version: ${project.version}
main: club.rigox.cherry.Cherry
api-version: 1.16
authors: [ sebastn_chan ]
description: Economy system for Vanilla atm
website: https://rigox.club
commands:
  credits:
    description: Credits command.
