name: Cherry

version: ${project.version}
main: club.rigox.cherry.Cherry
api-version: 1.16
authors: [ sebastn_chan ]
description: Economy system for Vanilla atm
depend:
  - VanillaCore
website: https://rigox.club
commands:
  credits:
    description: Credits command.
  cherry:
    description: Cherry command.
  pajin:
    description: Sos un pajin.
